#!/bin/bash

# Run code quality scripts before pushing the code to the repository.
# @see https://github.com/eaudeweb/drupal-code-qa-action

# Get the full path to the directory containing this script.
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "$SCRIPT_DIR/../../"

./code-qa.sh || true
