on:
  pull_request:
  push:
    branches:
      - master
name: 'QA - code quality'
jobs:
  qa-code:
    name: 'Check code quality'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: eaudeweb/drupal-install-action@v1.1
      - uses: eaudeweb/drupal-code-qa-action@v2.0