<?php

/**
 * @file
 * The edw module.
 */

use Drupal\edw_blocks\Plugin\Block\EdwSearchBlock;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function edw_blocks_theme($existing, $type, $theme, $path) {
  return [
    'edw_hero_banner_block' => [
      'variables' => [
        'title' => '',
        'breadcrumb' => '',
        'banner_image' => '',
        'image' => NULL,
        'summary' => '',
        'date' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_page_title().
 */
function edw_blocks_preprocess_block(&$variables) {
  // Hide the title and breadcrumbs block on pages
  // which should display the HeroBannerBlock.
  $banner_blocks = [
    'system_breadcrumb_block',
    'page_title_block',
  ];
  if (in_array($variables['plugin_id'], $banner_blocks)) {
    $route_match = \Drupal::routeMatch();
    $node = $route_match->getParameter('node');
    if ($node instanceof NodeInterface
      && $node->hasField('field_banner_image')
      && !$node->get('field_banner_image')->isEmpty()
    ) {
      $variables['content']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_block_alter().
 */
function edw_blocks_block_alter(&$definitions) {
  if (!empty($definitions['views_block:search-block_1'])) {
    $definitions['views_block:search-block_1']['class'] = EdwSearchBlock::class;
  }
}
