####
# 1. Configuration Requirements (for the DevOps setup)
#   * Configure the web server virtual host with document root on ${STAGING_PROJECT_DIR}/live directory
#   * Create the ${STAGING_PROJECT_DIR} directory on the target server owned by ${STAGING_SSH_USER}
#   * Create the ${STAGING_PROJECT_DIR}/files/default to store the public files for the project
#   * Create the ${STAGING_PROJECT_DIR}/settings.local.default.php to store the default settings.php custom settings
#   * Set up the repository secrets
#       - STAGING_PROJECT_DIR - Absolute path to the project root directory for the deployments (including `live` symlink)
#       - STAGING_SSH_USER - SSH account to connect to the server
#       - STAGING_SSH_KEY  - Private SSH key to connect to the server (public key configured on the server)
#       - STAGING_SSH_HOST - SSH host IP or public hostname
# 2. Configure below the triggers when deployment is running
####

on:
  push:
    branches:
      - 'staging'

name: 'staging instance'
jobs:
  deploy:
    name: 'deployment'
    runs-on: self-hosted
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: 'Install dependencies'
        uses: eaudeweb/drupal-install-action@main
        with:
          dev: false

      - name: 'Create release archive'
        id: artifact
        uses: eaudeweb/drupal-artifact-action@main

      - name: 'Deploy release on the server'
        uses: eaudeweb/drupal-deploy-action@main
        with:
          project_dir:      ${{ secrets.STAGING_PROJECT_DIR }}
          release_id:       ${{ steps.artifact.outputs.base }}
          release_filename: ${{ steps.artifact.outputs.filename }}
          ssh_user:         ${{ secrets.STAGING_SSH_USER }}
          ssh_host:         ${{ secrets.STAGING_SSH_HOST }}
          ssh_key:          ${{ secrets.STAGING_SSH_KEY }}

      - name: 'Update the Drupal instance'
        id: release
        uses: eaudeweb/drupal-update-action@v1
        with:
          path: ${{ secrets.STAGING_PROJECT_DIR }}/live
