####
# 1. Configure below the triggers when the checks are running
####

on: [pull_request]
name: "Run project tests"
jobs:
  qa-tests:
    name: "Run Drupal tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: eaudeweb/drupal-install-action@main
        with:
          dev: true

      - name: 'Run Drupal tests'
        uses: eaudeweb/drupal-runtests-action@main
